alter table public.cards
  add column if not exists original_page integer,
  add column if not exists matched_snapshot boolean,
  add column if not exists passcode text,
  add column if not exists card_status text,
  add column if not exists rank integer,
  add column if not exists link_rating integer,
  add column if not exists link_arrows text[] default '{}'::text[],
  add column if not exists pendulum_scale integer,
  add column if not exists monster_type_line text,
  add column if not exists monster_race text,
  add column if not exists monster_abilities text[] default '{}'::text[],
  add column if not exists spell_trap_property text,
  add column if not exists summoning_condition text,
  add column if not exists pendulum_effect text,
  add column if not exists support_tags text[] default '{}'::text[],
  add column if not exists anti_support_tags text[] default '{}'::text[],
  add column if not exists card_actions text[] default '{}'::text[],
  add column if not exists effect_types text[] default '{}'::text[];
